### ISSUE TITLE
Create questions

### ISSUE THREAD

**Issue by itsbriany** [EcoPet/EcoPet#19]
Create questions to ask the user so that they can think about how their habits affect the ecosystem

**Comment by th774141** [comment]
I am on this.I have a few great contacts. 

Q for the team? How many questions and what should be the user experience.  Assuming three questions with four choices?

**Comment by th774141** [comment]
Fish Population Question:
Do you eat sustainably sourced fish?
- All the time (Worst case)
- Sometimes (Average case)
- Never (Best case)

Water Level Question:
How many times do you run the washing machine/ dishwasher weekly?
- over 14 times(Worst case)
- 7-14 (Average case)
- 0-6(Best case)

Pollution Question:
How many packed goods did you consume over the past 2 days?
- 8+ (Worst case)
- 3-8 (Average case)
- Under 3 (Best case)
