### ISSUE TITLE
Alternate variables for UX- Which are the most interesting/ informative/ relevant

### ISSUE THREAD

**Issue by itsbriany** [EcoPet/EcoPet#34]
For example: Instead of asking how your habits affect the ocean level, ask how your habits would affect the C02 emissions.

**Comment by th774141** [comment]
I would incorporate emissions somehow - could be length of hot showers, time spent in a car versus on transit or a bike, number of lightbulbs on in your room, etc. This would be a cool one to visualize in an app too - emissions are absorbed by the oceans, which causes them to acidify. One of the most devastating effects of the acidification is coral bleaching - coral dies off, loses its colour, and fails to act as good habitat for other marine life. The entire ocean loses biodiversity as a result.

Another one is chemical waste from cleaning supplies and pesticides. When pesticides wash into the ocean, they cause eutrophication which is "blooms" of phytoplankton. The phytoplankton consume all of the ocean in the water, creating "dead zones" where there is no ocean left and all the other wildlife has suffocated. Other chemicals create toxic zones in their own right and I'm not exactly clear on which household chemicals are the worst for this, but will do some research. Would be cool to be able to look at what soaps, bleaches, laundry detergents, etc you used and see if they contain the really bad chemicals and suggestions for alternatives. Similarly, I'm sure certain foods are more pesticide-intensive than others.

Along the same line as the pesticide thing, it would be cool if people could input how many new articles of clothing they buy in a month. Cotton is  HUGELY pesticide-intensive crop (which makes me sad cause we are a clothing line). Buying new clothing could be one of the biggest ways people contribute to dead-zones.

Another smaller metric - a lot of tourism spots are ranked for how ocean-friendly they are. It looks at things like how they protect reefs from amateur divers, boats and anchors, how actively they work to keep tourist pollution out of the water and how they promote respect and awareness. When people travel, it would be cool if they could see the rankings of the place they are visiting.

These metrics are a lot to encourage people to use the app on a repetitive basis, so maybe they could just select from the metrics they are most interested in and choose which ones they want to measure on an ongoing basis.
